/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clinical;

/**
 *
 */
public class Enfermedades {

    public String Hipertension() {
        String info = "Afección en la que la presión de la sangre hacia las paredes de la arteria es demasiado alta.\n"
                + "Generalmente, la hipertensión se define como la presión arterial por encima de 140/90 y se considera grave cuando está por encima de 180/120.\n"
                + "\n"
                + "Sintomas: \n"
                + "En algunos casos, la presión arterial elevada no presenta síntomas. Si no se trata, con el tiempo, puede provocar trastornos de la salud, como enfermedades cardíacas y derrames cerebrales.\n"
                + "\n"
                + " Tratamientos: \n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "Ejercicio fisico \n"
                + "Control de estres \n"
                + "Dejar de fumar \n"
                + "Monitor de presion arterial casero \n"
                + "Dieta baja en sodio \n"
                + "\n"
                + "MEDICAMENTOS \n"
                + "\n"
                + " Inhibidor de la ECA \n"
                + "Relaja los vasos sanguineos, reduce la presion arterial y previene el daño renal relacionado con la diabetes \n"
                + "\n"
                + " Diuretico \n"
                + "Tomar medicina que ayuda a eliminar el exceso de agua del cuerpo. Tambien su receta para tratar su presion alta.\n"
                + "\n"
                + " Antihipertensivo \n"
                + "Reduce la presión arterial \n"
                + "\n"
                + " Bloqueador de los canales de calcio \n"
                + "Relaja los vasos sanguineos \n"
                + "\n"
                + " Beta bloqueador \n"
                + "Realentiza el ritmo cardiaco y reduce la presión arterial";
        return info;
    }

    public String Diabetes() {
        String info = "Caracterizada por alta concentración de azúcar en sangre (glucosa), debido a la incapacidad del organismo para aprovecharla, la diabetes se ha convertido en peligroso verdugo de la sociedad moderna, al grado que la mortalidad por esta causa supera las 85 mil defunciones al año.\n"
                + "\n"
                + " Sintomas: \n"
                + "- Hambre excesiva\n"
                + "- Sed excesiva o fatiga\n"
                + "- Aumento de peso o pérdida de peso\n"
                + "- Micción frecuente \n"
                + "- Mala sanación de heridas \n"
                + "- Visión borrosa\n"
                + "\n"
                + " Tratamientos:\n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "-Ejercicio fisico\n"
                + "-Dejar de fumar\n"
                + "-Adelgazamiento \n"
                + "-Fibra alimentaria\n"
                + "-Asesoria nutrimental\n"
                + "-Dieta para diabeticos \n"
                + "\n"
                + "MEDICAMENTOS \n"
                + "\n"
                + "-Insulina \n"
                + "-Antidiabeticos\n"
                + "-Estatina";
        return info;
    }

    public String Cancer() {
        String info = "Este señalamiento abarca varios tipos de cáncer, entre los que se incluyen el cáncer de mama, cáncer cervicouterino o cáncer de pulmón, por ejemplo. Los síntomas y tratamiento dependen del tipo de afección y de lo avanzada que esté; aunque se han logrado importantes avances al respecto, lo cierto es que la cifra de vidas que cobra este trastorno supera los 73 mil casos anuales.\n"
                + "\n"
                + " Sintomas:\n"
                + "\n"
                + "-Piel: lesión, enrojecimiento, protuberancia pequeña, pérdida de color, vasos sanguíneos inflamados en la piel o úlceras\n"
                + "-Áreas de dolor: huesos\n"
                + "-Urinarios: dificultad para iniciar y mantener un flujo constante de orina, flujo débil de orina, goteo de orina, micción excesiva por la noche, micción frecuente, necesidad urgente de orinar e incontinencia o retención urinaria\n"
                + "-Seno: bultos, molestia, pezón invertido o secreción del pezón\n"
                + "-También comunes: enrojecimiento o ganglios linfáticos inflamados\n"
                + "\n"
                + "Tratamientos:\n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "-Cirujia \n"
                + "-Terapia de rayos externos \n"
                + "-Radioterapia\n"
                + "-Braquiterapia\n"
                + "-Prostatectomia \n"
                + "-Electrocirujia\n"
                + "-Terapia fotodinamica\n"
                + "-Raspado de tejido\n"
                + "\n"
                + "MEDICAMENTOS \n"
                + "\n"
                + "-Modulador de estrogeno\n"
                + "-Quimioterapia\n"
                + "-Salud osea\n"
                + "-Tratamiento hormonal";
        return info;
    }

    public String influenza() {
        String info = "Provocada por virus, la influenza es infección respiratoria contagiosa que afecta nariz, garganta y pulmones originando una enfermedad leve o grave que incluso, lleve a la muerte. Según cifras oficiales, más de 15 mil 700 pacientes pierden la vida al año por esta causa.\n"
                + "\n"
                + "Sintomas:\n"
                + "\n"
                + "-Fiebre \n"
                + "-Escalofríos \n"
                + "-Deshidratación\n"
                + "-Dolores musculares\n"
                + "-Tos\n"
                + "-Congestión\n"
                + "-Secreción nasal\n"
                + "-Dolor de cabeza \n"
                + "-Fatiga\n"
                + "-Pérdida de apetito\n"
                + "-Dolor de garganta\n"
                + "-Sudoración\n"
                + "\n"
                + "Tratamientos:\n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "-Reposo en cama\n"
                + "-Suministracion de medicamentos\n"
                + "\n"
                + "MEDICAMENTOS\n"
                + "\n"
                + "-Descongestivo\n"
                + "-Antitusigeno\n"
                + "-Antinflamatorio\n"
                + "-Analgesico\n"
                + "-Antiviral";
        return info;
    }

    public String Obesidad() {
        String info = "En los últimos años ha crecido en forma alarmante el número de personas con exceso de peso, especialmente entre los niños, por lo que según la UNICEF (Fondo de las Naciones Unidas para la Infancia), México ocupa el primer lugar mundial en obesidad infantil, y el segundo en obesidad en adultos (precedido sólo por Estados Unidos).\n"
                + "\n"
                + "Sintomas:\n"
                + "\n"
                + "-Dolor articulaciones \n"
                + "-Dolor deespalda\n"
                + "-Sobrepeso\n"
                + "-Apetito desenfrenado\n"
                + "-Fatiga\n"
                + "-Grasa abdominal \n"
                + "-Ronquido\n"
                + "\n"
                + "Tratamiento:\n"
                + "\n"
                + "CUIDADO PERSONAL \n"
                + "\n"
                + "-Ejercicio físico\n"
                + "-Adelgazamiento\n"
                + "-Dieta reducida en carbohidratos\n"
                + "-Dieta baja en grasas\n"
                + "\n"
                + "MEDICAMENTOS\n"
                + "\n"
                + "-Terapia de comportamiento";
        return info;
    }

    public String Insuficiencia() {
        String info = "Enfermedad crónica de los riñones que lleva a la insuficiencia renal.\n"
                + "Los riñones filtran los desechos y el exceso de líquido de la sangre. Cuando fallan los riñones, los desechos se acumulan.\n"
                + "\n"
                + "Sintomas:\n"
                + "-Fatiga\n"
                + "-Malestar\n"
                + "-Presión arterial alta\n"
                + "-Pérdida de apetito \n"
                + "-Trastorno hidroelectrolítico\n"
                + "-Daño renal\n"
                + "-Hinchazón\n"
                + "-Insuficiencia renal\n"
                + "-Liquido en los pulmones\n"
                + "-Picazón\n"
                + "-Producción de orina insuficiente\n"
                + "-Pérdida de peso intensa e involuntaria\n"
                + "-Retraso del desarrollo \n"
                + "-Ritmo cardíaco anormal\n"
                + "\n"
                + "Tratamiento:\n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "-Dieta baja en proteinas\n"
                + "-Dialisis peritoneal \n"
                + "-Hemofiltracion \n"
                + "-Dialisis\n"
                + "\n"
                + "MEDICAMENTOS\n"
                + "\n"
                + "-Vitamina\n"
                + "-Agente reductor de calcio \n"
                + "-Esrimulante de la medula osea\n"
                + "-Diuretico";
        return info;

    }

    public String Colesterol() {
        String info = "Niveles elevados de colesterol en la sangre.\n"
                + "El colesterol elevado puede limitar la irrigación sanguínea y aumentar el riesgo de infartos o derrames cerebrales. Se detecta mediante un análisis de sangre.\n"
                + "\n"
                + "Sintomas:\n"
                + "\n"
                + "-Aneurisma de aorta\n"
                + "-Derrame cerebral\n"
                + "-Enfermedad arterial periférica\n"
                + "-Infarto agudo de miocardio\n"
                + "\n"
                + "Tratamiento:\n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "-Ejercicio Fisico\n"
                + "-Dieta baja en grasa\n"
                + "-Cumplimiento de horas de sueño\n"
                + "\n"
                + "MEDICAMENTOS\n"
                + "\n"
                + "-Estatina\n"
                + "-Medicacion para el colesterol";
        return info;

    }

    public String Depresion() {
        String info = "Trastorno de salud mental que se caracteriza por depresión persistente o pérdida de interés en las actividades, lo que puede causar dificultades significativas en la vida cotidiana.\n"
                + "Las causas posibles incluyen una combinación de fuentes biológicas, psicológicas y sociales de angustia. Cada vez son más las investigaciones que sugieren que estos factores pueden ocasionar cambios en la función cerebral, como la actividad anormal de ciertos circuitos neuronales en el cerebro.\n"
                + "\n"
                + "Sintomas:\n"
                + "\n"
                + "-Pérdida de interés o placer en hacer actividades\n"
                + "-Altibajos emocionales\n"
                + "-Ansiedad\n"
                + "-Apatía\n"
                + "-Culpa\n"
                + "-Descontento general\n"
                + "-Desesperanza\n"
                + "-Pérdida de interés o tristeza\n"
                + "-Agitación\n"
                + "-Aislamiento social\n"
                + "-Irritabilidad \n"
                + "-Llanto excesivo\n"
                + "-Despertar temprano\n"
                + "-Insomnio\n"
                + "-Somnolencia excesiva o sueño intranquilo\n"
                + "-Fatiga\n"
                + "-Hambre excesiva o pérdida de apetito\n"
                + "-Lentitud para realizar actividades, falta de concentración \n"
                + "-Pensamientos de suicidio\n"
                + "-Aumento de peso \n"
                + "-Pérdida de peso\n"
                + "-Análisis repetido de pensamientos \n"
                + "\n"
                + "Tratamiento:\n"
                + "\n"
                + "CUIDADO PERSONAL \n"
                + "\n"
                + "-Terapia cognitivo-conductual\n"
                + "-Terapia de comportamiento\n"
                + "-Psicoterapia\n"
                + "-Terapia electroconvulsiva \n"
                + "\n"
                + "MEDICAMENTOS \n"
                + "\n"
                + "-Antidepresivo\n"
                + "-Ansiolitico\n"
                + "-Antipsicotico\n"
                + "-Inhibidor selectivo de la recaptacion de la serotonina";
        return info;

    }

    public String Hipertiroidismo() {
        String info = "Afección en la que la glándula tiroides no produce suficiente hormona tiroidea.\n"
                + "La deficiencia de hormona tiroidea del hipotiroidismo puede afectar la frecuencia cardíaca, la temperatura corporal y todos los aspectos del metabolismo. El hipotiroidismo es más frecuente en las mujeres de edad avanzada.\n"
                + "\n"
                + "Exceso de producción de una hormona de la glándula con forma de mariposa ubicada en el cuello (tiroides).\n"
                + "El hipertiroidismo es la producción de demasiada hormona tiroxina. Puede aumentar el metabolismo.\n"
                + "\n"
                + "Sintomas:\n"
                + "\n"
                + "-Ftiga\n"
                + "-Hambre excesiva\n"
                + "-Intolerancia al calor o sudoración excesiva\n"
                + "-Agitación\n"
                + "-Hiperactividad o irritabilidad\n"
                + "-Palpitaciones\n"
                + "-Frecuencia cardíaca rápida o ritmo cardíaco anormal\n"
                + "-Nerviosismo\n"
                + "-Altibajos emocionales o ataque de pánico\n"
                + "-Ojos hinchados o protrusión anormal de los ojos\n"
                + "-Menstruación breve y leve o menstruación irregular\n"
                + "-Dificultad para quedarse dormido o insomnio\n"
                + "-Pérdida de peso\n"
                + "-Caída del cabello\n"
                + "-Debilidad muscular\n"
                + "-Diarrea\n"
                + "-Piel cálida o temblor\n"
                + "\n"
                + "Tratamiento:\n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "-Cirujia\n"
                + "-Cuidado personal \n"
                + "-Ejercicio controlado\n"
                + "\n"
                + "MEDICAMENTOS\n"
                + "\n"
                + "-Antitiroideo\n"
                + "-Beta bloqueador\n"
                + "-Hormonas\n"
                + "-Pastillas anticonceptivas\n"
                + "-Pastillas tiroideas";
        return info;

    }

    public String SIDA() {
        String info = "El VIH ocasiona el SIDA y, además, interfiere con la capacidad del cuerpo de combatir infecciones.\n"
                + "El virus se puede transmitir mediante el contacto con la sangre, el semen o los fluidos vaginales infectados.\n"
                + "\n"
                + "Sintomas:\n"
                + "\n"
                + "-Dolor abdominal\n"
                + "-Dolor al tragar\n"
                + "-Tos seca\n"
                + "-Fatiga\n"
                + "-Fiebre\n"
                + "-Malestar\n"
                + "-Pérdida de apetito\n"
                + "-Sudoración o sudores nocturnos\n"
                + "-Diarrea líquida\n"
                + "-Diarrea persistente\n"
                + "-Náusea o vómitos\n"
                + "-Hinchazón o llagas en la ingle\n"
                + "-Lengua blanca o úlceras\n"
                + "-Infección oportunista\n"
                + "-Dolor de cabeza\n"
                + "-Erupción cutánea\n"
                + "-Ganglios linfáticos inflamados\n"
                + "-Manchas rojas\n"
                + "-Neumonía\n"
                + "-Perdida de peso intensa e involuntaria o sapito\n"
                + "\n"
                + "Tratamiento:\n"
                + "\n"
                + "CUIDADO PERSONAL\n"
                + "\n"
                + "-Higiene personal \n"
                + "-Consumo de vitaminas\n"
                + "-Cuidado en las zonas intimas \n"
                + "\n"
                + "MEDICAMENTOS\n"
                + "\n"
                + "-Antiviral para el VIH";
        return info;

    }

    public String Covid() {
        String info = "La COVID-19 afecta de distintas maneras en función de cada persona. La mayoría de las personas que se contagian presentan síntomas de intensidad leve o moderada, y se recuperan sin necesidad de hospitalización.\n"
                + "\n"
                + "\n"
                + "Sintomas:\n"
                + "\n"
                + "-Fiebre\n"
                + "-Tos\n"
                + "-Cansancio\n"
                + "-Pérdida del gusto o del olfato\n"
                + "-Dolor de garganta\n"
                + "-Dolor de cabeza\n"
                + "-Molestias y dolores\n"
                + "-Diarrea\n"
                + "-Erupción cutánea o pérdida del color de los dedos de las manos o los pies\n"
                + "-Ojos rojos o irritados\n"
                + "\n"
                + "\n"
                + "Tratamiento:\n"
                + "-Coopera en los procedimientos de rastreo para frenar la propagación del virus.\n"
                + "-En caso de que no sea posible hacerte una prueba, quédate en casa y aíslate durante 14 días.\n"
                + "-Durante el periodo de cuarentena, no vayas al trabajo, a clase ni a lugares públicos. Si necesitas algo de fuera, pide a alguien que te lo lleve.\n"
                + "-Mantén una distancia de al menos 1 metro con otras personas, incluidos tus familiares.\n"
                + "-Usa la mascarilla para no contagiar a los demás. También debes llevarla puesta si necesitas acudir a un centro médico.\n"
                + "-Lávate las manos con frecuencia.\n"
                + "-Quédate en una habitación aislada del resto de los miembros de tu familia y, si no es posible, lleva puesta la mascarilla.\n"
                + "-Mantén la estancia bien ventilada.\n"
                + "-Si compartes el dormitorio con otras personas, debe haber una separación de al menos 1 metro entre las camas.\n"
                + "-Controla tus síntomas durante 14 días.\n"
                + "-Llama por teléfono a tu proveedor de servicios sanitarios de inmediato si tienes algún síntoma peligroso, como dificultad para respirar, pérdida de movilidad o del habla, confusión o dolor en el pecho.\n"
                + "-Mantén una actitud positiva. Para ello, puedes comunicarte con los tuyos por teléfono o por Internet, o hacer ejercicio en casa.";
        return info;

    }

}
