/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clinical;


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus Chavez
 */
public class FrmPadecimientos extends javax.swing.JFrame {

    /**
     * Creates new form FrmPadecimientos
     */
    public static Medico medicos;
    
    public FrmPadecimientos() {
        initComponents();

        Color fondo = new Color(134, 187, 216);
        this.getContentPane().setBackground(fondo);

        setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbDebilidad = new javax.swing.JCheckBox();
        cbTos = new javax.swing.JCheckBox();
        cbFatiga = new javax.swing.JCheckBox();
        cbHambre = new javax.swing.JCheckBox();
        cbFiebre = new javax.swing.JCheckBox();
        cbVisionBorrosa = new javax.swing.JCheckBox();
        cbDolor_Cab = new javax.swing.JCheckBox();
        cbAsintomatico = new javax.swing.JCheckBox();
        cbDiarrea = new javax.swing.JCheckBox();
        cbFrio = new javax.swing.JCheckBox();
        cbInsonmio = new javax.swing.JCheckBox();
        cbDolorGarga = new javax.swing.JCheckBox();
        cbDolor_musc = new javax.swing.JCheckBox();
        cbCongestion = new javax.swing.JCheckBox();
        cmbEnfer = new javax.swing.JComboBox<>();
        cbMolestias = new javax.swing.JCheckBox();
        cbPerdidaApetito = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_Desc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(134, 187, 216));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Padecimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        cbDebilidad.setText("Debilidad Muscular");

        cbTos.setText("Tos");

        cbFatiga.setText("Fatiga");

        cbHambre.setText("Hambre excesiva");

        cbFiebre.setText("Fiebre");

        cbVisionBorrosa.setText("Vision Borrosa");

        cbDolor_Cab.setText("Dolor de cabeza");

        cbAsintomatico.setText("Asintomatico");

        cbDiarrea.setText("Diarrea");

        cbFrio.setText("Frio");

        cbInsonmio.setText("Insomnio");

        cbDolorGarga.setText("Dolor de garganta");

        cbDolor_musc.setText("Dolor muscular");

        cbCongestion.setText("Congestion Nasal");

        cmbEnfer.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        cmbEnfer.setForeground(new java.awt.Color(0, 0, 0));
        cmbEnfer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Hipertension Arterial", "Diabetes", "Cáncer", "Influenza", "Obesidad", "Insificiencia renal", "Colesterol alto", "Depresion", "Hipertiroidismo", "SIDA", "Covid 19" }));
        cmbEnfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnferActionPerformed(evt);
            }
        });

        cbMolestias.setText("Molestias especificas");

        cbPerdidaApetito.setText("Perdida de apetito");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sintomas:");

        txtA_Desc.setColumns(20);
        txtA_Desc.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        txtA_Desc.setRows(5);
        jScrollPane1.setViewportView(txtA_Desc);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripcion:");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Padecimientos");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmbEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbTos)
                                            .addComponent(cbFatiga)
                                            .addComponent(cbFiebre)
                                            .addComponent(cbDolor_Cab)
                                            .addComponent(cbDiarrea)
                                            .addComponent(cbInsonmio)
                                            .addComponent(cbDolor_musc)
                                            .addComponent(cbMolestias))
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbDebilidad)
                                            .addComponent(cbPerdidaApetito)
                                            .addComponent(cbCongestion)
                                            .addComponent(cbDolorGarga)
                                            .addComponent(cbFrio)
                                            .addComponent(cbAsintomatico)
                                            .addComponent(cbVisionBorrosa)
                                            .addComponent(cbHambre)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addGap(119, 119, 119))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTos)
                            .addComponent(cbHambre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFatiga)
                            .addComponent(cbVisionBorrosa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFiebre)
                            .addComponent(cbAsintomatico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDolor_Cab)
                            .addComponent(cbFrio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDiarrea)
                            .addComponent(cbDolorGarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbInsonmio)
                            .addComponent(cbCongestion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDolor_musc)
                            .addComponent(cbPerdidaApetito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMolestias)
                            .addComponent(cbDebilidad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEnferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnferActionPerformed

        int pos = cmbEnfer.getSelectedIndex();
        Enfermedades e = new Enfermedades();
        if (pos == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una opción");
        }

        if (pos == 1) { //Hipertencion Arterial
            txtA_Desc.setText(e.Hipertension());

            cbAsintomatico.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbTos.setSelected(false);
            cbPerdidaApetito.setSelected(false);
            cbMolestias.setSelected(false);
            cbInsonmio.setSelected(false);
            cbHambre.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbFatiga.setSelected(false);
            cbDolor_musc.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbDebilidad.setSelected(false);
            cbCongestion.setSelected(false);

        }

        if (pos == 2) { //Diabetes
            txtA_Desc.setText(e.Diabetes());

            cbDebilidad.setSelected(true);
            cbHambre.setSelected(true);
            cbVisionBorrosa.setSelected(true);
            cbInsonmio.setSelected(true);

            cbTos.setSelected(false);
            cbPerdidaApetito.setSelected(false);
            cbMolestias.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbFatiga.setSelected(false);
            cbDolor_musc.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);

        }

        if (pos == 3) { //Cancer
            txtA_Desc.setText(e.Cancer());
            cbFatiga.setSelected(true);
            cbMolestias.setSelected(true);
            cbDolor_musc.setSelected(true);
            cbPerdidaApetito.setSelected(true);
            cbDebilidad.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbTos.setSelected(false);
            cbInsonmio.setSelected(false);
            cbHambre.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);
        }

        if (pos == 4) { //Influenza
            txtA_Desc.setText(e.influenza());
            cbCongestion.setSelected(true);
            cbTos.setSelected(true);
            cbDolor_Cab.setSelected(true);
            cbFiebre.setSelected(true);
            cbDolor_musc.setSelected(true);
            cbPerdidaApetito.setSelected(true);
            cbDebilidad.setSelected(true);
            cbDolorGarga.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbMolestias.setSelected(false);
            cbInsonmio.setSelected(false);
            cbHambre.setSelected(false);
            cbFrio.setSelected(false);
            cbFatiga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbAsintomatico.setSelected(false);
        }

        if (pos == 5) { //Obesidad
            txtA_Desc.setText(e.Obesidad());
            cbDolor_musc.setSelected(true);
            cbHambre.setSelected(true);
            cbMolestias.setSelected(true);
            cbFatiga.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbTos.setSelected(false);
            cbPerdidaApetito.setSelected(false);
            cbInsonmio.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbDebilidad.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);

        }

        if (pos == 6) { //Insufiencia renal
            txtA_Desc.setText(e.Insuficiencia());
            cbFatiga.setSelected(true);
            cbPerdidaApetito.setSelected(true);
            cbMolestias.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbTos.setSelected(false);
            cbInsonmio.setSelected(false);
            cbHambre.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbDolor_musc.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbDebilidad.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);

        }

        if (pos == 7) { //Colesterol alto
            txtA_Desc.setText(e.Colesterol());
            cbMolestias.setSelected(true);
            cbDolor_musc.setSelected(true);
            cbInsonmio.setSelected(true);
            cbVisionBorrosa.setSelected(true);

            cbTos.setSelected(false);
            cbPerdidaApetito.setSelected(false);
            cbHambre.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbFatiga.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbDebilidad.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);
        }

        if (pos == 8) { //Colesterol alto
            txtA_Desc.setText(e.Colesterol());
            cbMolestias.setSelected(true);
            cbDolor_musc.setSelected(true);
            cbInsonmio.setSelected(true);
            cbVisionBorrosa.setSelected(true);

            cbTos.setSelected(false);
            cbPerdidaApetito.setSelected(false);
            cbHambre.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbFatiga.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbDebilidad.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);

        }
        if (pos == 9) { //Depresion
            txtA_Desc.setText(e.Depresion());
            cbFatiga.setSelected(true);
            cbInsonmio.setSelected(true);
            cbPerdidaApetito.setSelected(true);
            cbDebilidad.setSelected(true);
            cbFrio.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbTos.setSelected(false);
            cbMolestias.setSelected(false);
            cbHambre.setSelected(false);
            cbFiebre.setSelected(false);
            cbDolor_musc.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDiarrea.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);
        }

        if (pos == 10) { //Hipotireidismo
            txtA_Desc.setText(e.Hipertiroidismo());
            cbFatiga.setSelected(true);
            cbHambre.setSelected(true);
            cbDiarrea.setSelected(true);
            cbDebilidad.setSelected(true);
            cbDolor_musc.setSelected(true);
            cbPerdidaApetito.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbTos.setSelected(false);
            cbMolestias.setSelected(false);
            cbInsonmio.setSelected(false);
            cbFrio.setSelected(false);
            cbFiebre.setSelected(false);
            cbDolor_Cab.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);
        }
        if (pos == 11) { //SIDA
            txtA_Desc.setText(e.SIDA());
            cbTos.setSelected(true);
            cbFatiga.setSelected(true);
            cbFiebre.setSelected(true);
            cbPerdidaApetito.setSelected(true);
            cbDiarrea.setSelected(true);
            cbDolor_Cab.setSelected(true);
            cbMolestias.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbInsonmio.setSelected(false);
            cbHambre.setSelected(false);
            cbFrio.setSelected(false);
            cbDolor_musc.setSelected(false);
            cbDolorGarga.setSelected(false);
            cbDebilidad.setSelected(false);
            cbCongestion.setSelected(false);
            cbAsintomatico.setSelected(false);
        }

        if (pos == 11) { //COVID
            txtA_Desc.setText(e.Covid());
            cbTos.setSelected(true);
            cbFatiga.setSelected(true);
            cbFiebre.setSelected(true);
            cbDolorGarga.setSelected(true);
            cbDiarrea.setSelected(true);
            cbDolor_Cab.setSelected(true);
            cbAsintomatico.setSelected(true);
            cbFrio.setSelected(true);
            cbCongestion.setSelected(true);

            cbVisionBorrosa.setSelected(false);
            cbPerdidaApetito.setSelected(false);
            cbMolestias.setSelected(false);
            cbInsonmio.setSelected(false);
            cbHambre.setSelected(false);
            cbDolor_musc.setSelected(false);
            cbDebilidad.setSelected(false);
        }


    }//GEN-LAST:event_cmbEnferActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JCheckBox cbAsintomatico;
    private javax.swing.JCheckBox cbCongestion;
    private javax.swing.JCheckBox cbDebilidad;
    private javax.swing.JCheckBox cbDiarrea;
    private javax.swing.JCheckBox cbDolorGarga;
    private javax.swing.JCheckBox cbDolor_Cab;
    private javax.swing.JCheckBox cbDolor_musc;
    private javax.swing.JCheckBox cbFatiga;
    private javax.swing.JCheckBox cbFiebre;
    private javax.swing.JCheckBox cbFrio;
    private javax.swing.JCheckBox cbHambre;
    private javax.swing.JCheckBox cbInsonmio;
    private javax.swing.JCheckBox cbMolestias;
    private javax.swing.JCheckBox cbPerdidaApetito;
    private javax.swing.JCheckBox cbTos;
    private javax.swing.JCheckBox cbVisionBorrosa;
    private javax.swing.JComboBox<String> cmbEnfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA_Desc;
    // End of variables declaration//GEN-END:variables
}
